[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "krautils"
version = "0.4.0"
description = "A python package for parsing, merging, and analyzing Kraken2 output files."
authors = [{name = "Andrea Telatin", email = "andrea.telatin@quadram.ac.uk"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["kraken2", "taxonomy", "bioinformatics", "metagenomics"]
urls = {Homepage = "https://quadram-institute-bioscience.github.io/kraut", Repository = "https://github.com/quadram-institute-bioscience/kraut", Issues = "https://github.com/quadram-institute-bioscience/kraut/issues"}

requires-python = ">=3.10"
dependencies = [
    "pandas",
    "typer",
    "rich",
    "click",
    "matplotlib",
    "plotly",
    "scikit-bio>=0.7"
]

[project.scripts]
kraut = "kraut.commands.cli:app"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["kraut*"]
exclude = ["db*", "data*", "kraken*", "scrapbook*"]
